### ISSUE TITLE
Pathological dataset using multiple scales

### ISSUE THREAD

**Issue by simonverret** [simonverret/deep_continuation#9]
The idea is to get a hard dataset when used without rescaling, to showcase the output degenerancy, and measure to what extent rescaling solves it.

In principle, the rescaling turns output degenerancy into input degenerancy.

**Comment by amstremblay** [comment]
Bonjour Simon,
Il faudrait qu'on se rencontre pour discuter de ce projet quand tu auras le temps. J'espère que tout va bien.
André-Marie

De : Simon Verret ***@***.***>
Envoyé : 21 avril 2022 22:39
À : simonverret/deep_continuation ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [simonverret/deep_continuation] Pathological dataset using multiple scales (purposefully hard without rescaling) (Issue #9)


-

**Comment by simonverret** [comment]
Better idea: use a single p(x), generate a whole dataset using random s. Rescaling will make all spectra collapse on the same target. Without rescaling, the dataset is probably as hard as usual. To confirm.
